apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-analysis
  namespace: demo
spec:
  metrics:
  - name: success-rate
    interval: 5m
    # 🌟 BẮT BUỘC PHẢI THÊM [0] VÀO ĐÂY:
    successCondition: result[0] >= 0.95   
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        query: |
          sum(rate(flask_http_request_total{namespace="demo", status!~"5.."}[2m])) 
          / 
          sum(rate(flask_http_request_total{namespace="demo"}[2m]))